import type { NextPage } from 'next'
import Head from 'next/head'

import Balance from 'components/Balance'
import Header from 'components/Header'
import Transactions from 'components/transactions'
import Payment from 'components/payment'
import Movements from 'components/movements'
import Navbar from 'components/navbar'

const Home: NextPage = () => {
	return (
		<section className="page-container">
			<Head>
				<title>Bank | Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header>
				<Balance />
			</Header>
			<Transactions>
				<Payment />
			</Transactions>
			<Movements />
			<Navbar />
		</section>
	)
}

export default Home
