import type { NextPage } from 'next'
import Head from 'next/head'

import Balance from 'components/Balance'
import Header from 'components/Header'
import Transactions from 'components/transactions'
import Payment from 'components/payment'
import Movements from 'components/movements'
import Navbar from 'components/navbar'
import { Fragment } from 'react'

const Home: NextPage = () => {
	return (
		<section className="home">
			<Head>
				<title>Bank | Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Transactions>
				<Fragment>
					<div className="home__balance">
						<Balance title="SALDO DISPONIBLE" />
					</div>
					<div className="home__payment">
						<Payment />
					</div>
				</Fragment>
			</Transactions>
			<Movements />
			<div className="home__navbar">
				<Navbar />
			</div>
		</section>
	)
}

export default Home
